# Site settings
name: Color Box Design and Letterpress
title: Color Box Design and Letterpress
email: jacobsiddall@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A site for Color Box Design and Letterpress
# baseurl: "/cadence" # the subpath of your site, e.g. /blog
url: "http://tbd.com" # the base hostname & protocol for your site
twitter_username: jjsiddall
github_username:  jjsiddall

# Build settings
markdown: kramdown
